### ISSUE TITLE
Deprecate this lib in favour of https://github.com/zcash-hackworks/bitcore-lib-zcash

### ISSUE THREAD

**Issue by daira** [BitMEX/zcash-bitcore-lib#9]
The latter supports Overwinter and is maintained.

**Comment by STRML** [comment]
Thanks, done.

**Comment by LitecoinZ** [comment]
Hi @daira I have an issue with https://github.com/zcash-hackworks/bitcore-lib-zcash

V4 transactions are not created correctly due a bad signature.Can you please help me to fix it?

Thanks
Mark
